name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -t rsa 51.20.255.121 >> $HOME/.ssh/known_hosts
        chmod 644 $HOME/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa ubuntu@51.20.255.121 "cd /home/ubuntu/Dice-Assignment-3 && docker-compose up -d"