name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH Key
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/aws_vm.pem
        chmod 600 $HOME/.ssh/aws_vm.pem
        ssh-keyscan ec2-51-20-255-121.eu-north-1.compute.amazonaws.com >> $HOME/.ssh/known_hosts
        chmod 644 $HOME/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws_vm.pem ubuntu@ec2-51-20-255-121.eu-north-1.compute.amazonaws.com "cd /home/ubuntu/Dice-Assignment-3 && docker-compose up -d"
