name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build and Run Docker Compose on EC2 using AWS SSM
      run: |
            instance_id="i-0123456789abcdef0"  # Replace with your actual instance ID
            echo "Instance ID: $instance_id"
            aws ssm send-command --instance-ids "$instance_id" --document-name "AWS-RunShellScript" --parameters commands=["cd /home/ubuntu/Dice-Assignment-3","docker-compose up -d"]