name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "$SSH_KEY" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan -t rsa ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Build and Run Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -l ${{ secrets.REMOTE_USER }} ${{ secrets.REMOTE_HOST }} \
          "cd /home/ubuntu/Dice-Assignment-3 && docker-compose up -d"
