name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        VERSION: "1.0.0"
        PUBLICIP: "51.20.73.233"
        PROJECT_NAME: "/home/ubuntu/Dice-Assignment-3"
        USERNAME: "ubuntu"
        PORT: "22"

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Configure SSH
          uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: SSH into server and Pull branch
          run: |
            ssh -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.PUBLICIP }} "cd ${{ env.PROJECT_NAME }} && git pull"

        - name: Run Docker Compose
          run: |
            ssh -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.PUBLICIP }} "cd ${{ env.PROJECT_NAME }} && docker-compose down && docker-compose up -d --build"
# addcomment

## add comment again