name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: softprops/action-ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Build and Run Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -l ${{ secrets.REMOTE_USER }} ${{ secrets.REMOTE_HOST }} \
          "cd /home/ubuntu/Dice-Assignment-3 && docker-compose up -d"
